services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: rosterdb
      POSTGRES_USER: rosteruser
      POSTGRES_PASSWORD: Mutabor_123!
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" # WICHTIG: Nur lokal, für SSH-Tunnel
    networks:
      - app-network


  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080" # Optional: nur zum Debuggen freigeben
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=ZWluc3VwZXJzaWNoZXJlcmNvZGVmdWVybWVpbmVmYW50YXNpc2NoZWFwcGVuZGxpY
      # DB Verbindung überschreiben (zeigt auf den Service 'db')
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rosterdb
      - SPRING_DATASOURCE_USERNAME=rosteruser
      - SPRING_DATASOURCE_PASSWORD=Mutabor_123!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      # Update: Tabellen automatisch erstellen/anpassen
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80" # Wir mappen Port 3000 nach außen (oder 80, wenn du keinen Host-Nginx willst)
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge